fix = true
target-version = "py311"

# Include only specific directories
include = ["core/**/*.py", "scripts/**/*.py"]

line-length = 88

[lint]
select = ["E", "W", "F", "I", "N", "UP", "B", "C4", "T20"]
ignore = ["E501"]

[pydocstyle]
convention = "google"
