# TODO: split to multi config
prior_settings:
  name: prior_name
posterior_settings:
  name: posterior_name
experiment_settings:
  dataset:
    dataset_name: mnist
    dataset_path: ./data/mnist/
  split_strategy:
    split_strategy_name: pbp
    batch_size: 250,
    training_percent: 1.0
    val_percent: 0.05
    prior_percen: 0.5
