training_pipeline:
  training_pipeline_name: pbp
  model: abc
evaluation_pipeline:
  evaluation_pipeline_name: pbp
dataset:
  dataset_name: mnist
  dataset_path: ./data/mnist/
split_strategy:
  split_strategy_name: pbp
  batch_size: 250
  training_percent: 1.0
  val_percent: 0.05
  prior_percent: 0.5
  prior_type: learnt   # learnt, not_learnt
  self_certified: True  # True, False, None
  seed: 7
  dataset_loader_seed: 10
